### ISSUE TITLE
Parsing error: Unexpected character '@' when using decorators

### ISSUE THREAD

**Issue by mikeycgto** [rollup/rollup-plugin-babel#145] opened 2017-06-15 13:48 UTC
I'm getting a parser error when I try to use decorators in my project. The specific error is:

```
src/components/Main.jsx
  53:5  error  Parsing error: Unexpected character '@'
```

Here is my babel rollup from `config.js` configuration file:

```js
        babel({
            exclude: 'node_modules/**',
            babelrc: false,

            plugins: [
                'external-helpers',
                'transform-decorators-legacy',
                'transform-class-properties'
            ],

            presets: [
                ['es2015', { modules: false }], 'stage-0', 'react'
            ]
        })
```

I'm using `rollup -c config.js --output app.js app.jsx` to build my project. I have `babel-plugin-transform-decorators-legacy` installed (v1.3.4) as well as the latest versions of rollup and this plugin.

I don't think I am doing anything wrong and have everything I need installed and configured properly. Any ideas? Thanks for any help or insight!

**Comment by pixelatorz** [comment] 2018-01-04 14:59
got a similar issue with class variables despite I do import '@babel/preset-stage-1'

**Comment by freakboy3742** [comment] 2018-01-07 01:02
I think this may be related to ordering of plugins. The `@` character is a syntactic change introduced by ESnext, so you need to apply the `babel()` transform *before* you do any other processing on a file that includes it. 

In my project, I had the `babel()` transform at the end of the plugins list; moving it to the start fixed the issue. I needed to put it *after* the `json()` plugin (for similar syntactic reasons; the json plugin needs to resolve syntactic problems before the babel plugin can run), but as long as it's in the pipeline before any other processing occurs on the script that contains decorators, you should be good.

You can also use the newer ESnext decorator definition by using `transform-decorators` rather than `transform-decorators-legacy`. There are some subtle changes in decorator definition and execution order, but `transform-decorators` implements the proposal that is most likely to be accepted into ES2017. You may also need to add the `stage-1` preset, because of the status of the decorators proposal.

**Comment by pixelatorz** [comment] 2018-01-07 10:47
indeed is had to do with the layer oder. 
However I have another issue, this is my current rollup config

`import npm from 'rollup-plugin-node-resolve';
import babel from 'rollup-plugin-babel';
import commonjs from 'rollup-plugin-commonjs';
import nodeResolve from 'rollup-plugin-node-resolve';

export default {
  plugins: [
    npm(),
    babel({
      babelrc: false,
      presets: [
        [
          '@babel/preset-env',
          {
            modules: false
          }
        ],
        [
          '@babel/preset-stage-1'
        ]
      ]
    }),
    nodeResolve({
      jsnext: true,
      main: true
    }),
    commonjs()
  ]
};
`

the problem is now with openlayers in the node_modules, where they do imports of functions: 
`
import _ol_renderer_vector_ from '../vector.js';
 `
which conflicts in the babel plugin. still got to find a solution for that

**Comment by Andarist** [comment] 2018-06-21 22:33
Closing this as outdated and not actionable here - this plugin just runs babel with specified options over your files, it doesn't actually care what transforms etc you are using. If there is some parsing error it means that you have configured your babelrc wrongly somehow.

**Closed by Andarist** 2018-06-21 22:33 UTC

**Comment by jhpratt** [comment] 2019-07-01 02:11
@Andarist My code builds as expected with just Babel. Introducing Rollup into the mix breaks things.

**Comment by Andarist** [comment] 2019-07-02 09:07
@jhpratt To get help you'd have to share a repository with the issue reproduced. Can't help you without seeing how exactly you have setup your project.
