### ISSUE TITLE
Error when using `typeof` babelHelper

### ISSUE THREAD

**Issue by joeldenning** [rollup/rollup-plugin-babel#40] opened 2016-02-10 01:14 UTC
I get an error `A module cannot import itself (/Users/joel/workplace/primary-navbar/node_modules/babel-runtime/helpers/typeof.js)` when I run rollup with the following config. I am using the transform-runtime plugin as per the readme for this repo (rollup-plugin-babel). From what I can tell, `.../helpers/typeof.js` does not import itself like the error message indicates.

Would love any help on it if my code is misconfigured, or if this is a bug in rollup/rollup-plugin-babel I'd be happy to pull request a fix!

Here is my rollup.config.js:

```
import commonjs from 'rollup-plugin-commonjs';
import nodeResolve from 'rollup-plugin-node-resolve';
import babel from 'rollup-plugin-babel';

export default {
    entry: 'src/primary-navbar.js',
    dest: 'lib/primary-navbar.js',
    plugins: [
        nodeResolve({
            jsnext: true,
            main: true,
            skip: [
                'canopy-urls!sofe'
            ],
        }),

        commonjs({
            include: 'node_modules/**',
        }),

        babel({
            presets: ['es2015-rollup'],
            plugins: ['transform-object-rest-spread', 'transform-runtime'],
            runtimeHelpers: true,
        }),
    ],
    format: 'es6'
}
```

And for reference, here is the babel source code that is supposedly importing itself:

```
"use strict";

var _typeof = typeof _Symbol === "function" && typeof _Symbol$iterator === "symbol" ? function (obj) { return typeof obj; } : function (obj) { return obj && typeof _Symbol === "function" && obj.constructor === _Symbol ? "symbol" : typeof obj; };

exports.__esModule = true;

var _iterator = require("../core-js/symbol/iterator");

var _iterator2 = _interopRequireDefault(_iterator);

var _symbol = require("../core-js/symbol");

var _symbol2 = _interopRequireDefault(_symbol);

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

exports.default = typeof _symbol2.default === "function" && _typeof(_iterator2.default) === "symbol" ? function (obj) {
  return typeof obj === "undefined" ? "undefined" : _typeof(obj);
} : function (obj) {
  return obj && typeof _symbol2.default === "function" && obj.constructor === _symbol2.default ? "symbol" : typeof obj === "undefined" ? "undefined" : _typeof(obj);
};
```

**Comment by Victorystick** [comment] 2016-02-12 17:21
@joeldenning If you try to _transform_ the typeof-helper using Babel, it should detect that the `typeof` keyword is used, which means that the helper must be transformed to use the typeof-helper.

That's a possible reason why you're getting the error. Can you determine if that's the case?

**Comment by joeldenning** [comment] 2016-02-14 00:14
Based on what I can tell, it seems like your guess may be correct. The full stack trace is the following:

```
A module cannot import itself (/Users/joel/workplace/primary-navbar/node_modules/babel-runtime/helpers/typeof.js)
Error: A module cannot import itself (/Users/joel/workplace/primary-navbar/node_modules/babel-runtime/helpers/typeof.js)
    at /Users/joel/.nvm/versions/node/v4.0.0/lib/node_modules/rollup/www/ROLLUP/rollup/src/Bundle.js:181:14
    at tryCatch (/Users/joel/.nvm/versions/node/v4.0.0/lib/node_modules/rollup/www/ROLLUP/rollup/node_modules/es6-promise/lib/es6-promise/-internal.js:182:12)
    at invokeCallback (/Users/joel/.nvm/versions/node/v4.0.0/lib/node_modules/rollup/www/ROLLUP/rollup/node_modules/es6-promise/lib/es6-promise/-internal.js:194:13)
    at publish (/Users/joel/.nvm/versions/node/v4.0.0/lib/node_modules/rollup/www/ROLLUP/rollup/node_modules/es6-promise/lib/es6-promise/-internal.js:165:7)
    at flush (/Users/joel/.nvm/versions/node/v4.0.0/lib/node_modules/rollup/www/ROLLUP/rollup/node_modules/es6-promise/lib/es6-promise/asap.js:88:5)
    at doNTCallback0 (node.js:407:9)
    at process._tickCallback (node.js:336:13)
```

Digging into the rollup source code a bit, it looks like [rollup may indeed be trying to resolve/transform](https://github.com/rollup/rollup/blob/master/src/Bundle.js#L177-L207) `node_modules/babel-runtime/helpers/typeof.js`.

I looked into it a bit more and it seems that this issue may be caused by the combination of `rollup-plugin-commonjs`, `rollup-plugin-npm`, and `rollup-plugin-commonjs`. In my rollup.config.js, if I move the babel plugin to be before the commonjs, I get a different error (`Error parsing /Users/joel/workplace/primary-navbar/node_modules/babel-runtime/node_modules/core-js/library/fn/json/stringify.js: 'import' and 'export' may only appear at the top level (4:0) in /Users/joel/workplace/primary-navbar/node_modules/babel-runtime/node_modules/core-js/library/fn/json/stringify.js`).

I also tried removing `include: 'node_modules/**'` from my commonjs plugin, but that didn't do anything. It seems to be the order in which I declare the plugins that causes different issues.

**Comment by TrySound** [comment] 2016-02-14 00:23
@joeldenning `rollup-plugin-npm` was renamed to `rollup-plugin-node-resolve`.

**Comment by joeldenning** [comment] 2016-02-14 00:27
@TrySound yeah I noticed that a week or two ago, must have just mispoke in my comment :). If you take a look at the code in my comments, though, you'll see that I am indeed using `rollup-plugin-node-resolve`.

**Comment by TrySound** [comment] 2016-02-14 00:29
@joeldenning Ops, sorry. Auto reviewing mode :)

**Comment by philer** [comment] 2016-04-03 20:15
I just ran into the same issue (glad I'm not alone). After spending ages figuring out how to make rollup play with babel's runtime transformation it seems I've finally hit the correct configuration only to have it blow up in my face.

I found a solution / work-around: Using the `exclude` in babel's configuration to prevent it from transpiling itself (as recommended in the [readme of `rollup-plugin-babel`](https://github.com/rollup/rollup-plugin-babel#usage)):
```JS
const babelOptions = {
  presets: ['es2015-rollup', 'stage-2'],
  runtimeHelpers: true,
  exclude: 'node_modules/babel-runtime/**',
  plugins: ['transform-runtime'],
};
```
However things didn't end there. As a result I'm now getting a new error of similar nature:
__`Module /…/node_modules/babel-runtime/core-js/object/create.js does not export default (imported by …)`__
The file in question looks like this:
```JS
module.exports = { "default": require("core-js/library/fn/object/create"), __esModule: true };
```
I ended up installing `rollup-plugin-commonjs` which I was not using previously (unlike @joeldenning). This solved the issue, although I'm now facing a massive output warning me about potentially bad ordering due to cyclic dependencies. I haven't had an opportunity to test my output file yet.

**Comment by arbesfeld** [comment] 2016-11-09 21:51
I am also seeing this issue - is there any fix for when using `commonjs` `node-resolve` and `babel` with runtime-helpers?

**Comment by lygstate** [comment] 2016-11-12 17:34
so is me

**Comment by lygstate** [comment] 2016-11-12 17:36
I solved this issue in two stage

**Comment by Rich-Harris** [comment] 2016-12-13 17:03
Sorry for the very slow response here – can anyone provide a minimal reproduction? I don't have enough information here to investigate. Thanks

**Comment by Andarist** [comment] 2018-06-21 22:16
Closing this as outdated and not actionable due to lack of reproduction case. Feel free to open new issue.

**Closed by Andarist** 2018-06-21 22:16 UTC
Labels: more information needed

**Comment by dszakallas** [comment] 2019-02-19 21:11
I have exactly the same issue. The circular dependencies actually cause an endless recursion inside typeof.
