### ISSUE TITLE
Some strange error with well-known "length of undefined"

### ISSUE THREAD

**Issue by olstenlarck** [rollup/rollup-plugin-babel#172] opened 2017-10-24 23:18 UTC
It is very very very strange, cuz before some days and weeks i used exactly that version (3.0.2) of this plugin and exactly Rollup `0.50.0`.

Rollup config (pretty basic and simplified example)

```js
const babelPlugin = require('rollup-plugin-babel');
module.exports = {
  input: 'src/foo.js',
  output: {
    file: 'dist/foo.js',
    format: 'es',
  },
  plugins: [babelPlugin()]
};
```

src/foo.js

```js
module.exports = () => 123;
```

no `.babelrc` file and no such options passed anywhere. It's not a problem, since it will just copy the file in that case when there is no needed transformations. Intentionally don't add anything, cuz it fails anyway.

Also tried to remove node_modules and yarn.lock, clearing cache and etc.

**Comment by olstenlarck** [comment] 2017-10-24 23:19
Okey. Debugged pretty successfully. It comes when `babel-core@7.0.0-beta.3` is used.

**Comment by lukastaegert** [comment] 2017-10-25 04:39
Hi @olstenlarck,
I tried to reproduce your issue but was not successful even though I tried to force the babel-core version you mentioned. Maybe this is also related to the node version you use? I am on node 8.7 but it is possible the problem only occurs in some earlier version?

Beyond that, it would be interesting to see if #170 helps with this issue. Unfortunately it is not merged yet and this plugin does not yet support installation from github so one would have to check it out and use `npm link` to try it out.

**Comment by olstenlarck** [comment] 2017-10-25 05:51
> Maybe this is also related to the node version you use? I am on node 8.7 but it is possible the problem only occurs in some earlier version?

Same here - everything is latest always :D (archlinux / rolling release fan here), so yea it is 8.7.

I'll just stick to the babel 6.26 for now, it's not a problem.

**Comment by nicolo-ribaudo** [comment] 2017-10-25 06:32
Does Babel (without rollup) throw the same error?

**Comment by olstenlarck** [comment] 2017-10-25 06:49
Don't know.

**Comment by goto-bus-stop** [comment] 2017-10-26 14:41
I'm getting this too, caused by `transformed.metadata.usedHelpers` being used on line 69:

https://github.com/rollup/rollup-plugin-babel/blob/a5f16de276c9a55bf6989797c2d6cda46201d5ed/src/index.js#L66-L69

#170 does fix it for me 🎉

**Comment by olstenlarck** [comment] 2017-10-26 18:30
@goto-bus-stop, yea i thought that may be the problem. But didn't review the code deeply.

**Comment by Andarist** [comment] 2017-10-28 12:57
@lukastaegert mentioned PR supports installation directly from the github, I've added the `prepare` script last week to it

**Comment by francoisromain** [comment] 2017-11-29 13:47
@Andarist I have the `[!] (babel plugin) TypeError: Cannot read property 'length' of undefined` too. 

- rollup 0.52
- rollup-plugin-babel: 3.0.2
- @babel/core: 7.0.0-beta.32. 

I tried to install rollup-plugin-babel: "rollup/rollup-plugin-babel#fix/external-helpers-babel-7" but it did not match any file(s) known to git. 

What could I do to avoid the bug? Thank you

**Comment by Andarist** [comment] 2017-11-29 13:50
@francoisromain try `npm install --save-dev rollup@4.0.0-beta.0`

**Comment by francoisromain** [comment] 2017-11-29 16:27
do you mean `npm install --save-dev rollup-plugin-babel@4.0.0-beta.0`?
It seems to work but now I have a new error with postcss: 
```
(babel plugin) SyntaxError: /Volumes/Fr-01-Work/Sites/camomile-ui/src/css/styles.css: This experimental syntax requiresenabling one of the following parser plugin(s): 'decorators, decorators2' (3:0)
> 1 | @import 'settings.css';
```
Do you have a hint?

**Comment by francoisromain** [comment] 2017-11-29 16:54
I installed `https://github.com/rollup/rollup-plugin-json` and it works now. Thank you very much

**Comment by looeee** [comment] 2018-02-06 00:10
I tried `npm install --save-dev rollup-plugin-babel@4.0.0-beta.0` and `npm install --save-dev rollup-plugin-babel@4.0.0-beta.1` but then I get a new error: 

`Error: Cannot find module '@babel/core'`

Even though I do have `babel-core@6.26.0` installed.

**Comment by olstenlarck** [comment] 2018-02-06 01:19
@looeee it obvious. They are different. Install `@babel/core` specially. It wants it because is peer dep.

I'm closing cuz i don't have any problems any more.

```
yarn add --dev rollup@latest # 0.55+
yarn add --dev @babel/core rollup-plugin-babel@4
```

**Comment by looeee** [comment] 2018-02-06 02:27
@olstenlarck not sure I understand. I'm using npm, are you saying that 'babel-core' and 'babel/core' are different packages? 

I do have  'babel-core' installed. If I roll back to non beta version of 'rollup-plugin-babel' then they error goes away, but I'm back to the previous error.

**Comment by olstenlarck** [comment] 2018-02-06 03:06
Yes they are. They are different versions and future is to use `@babel` namespace to install them. All of the namespaced packages uses Babel v7 and are in sync to each other.

**Closed** 2018-02-06 03:32 UTC

**Comment by looeee** [comment] 2018-02-06 03:49
Wow, keeping up with these poorly/undocumented API changes over the last few Babel releases is a real headache...

**Comment by olstenlarck** [comment] 2018-02-06 04:06
Follow their blog, at least. Docs about v6 are good to me, it is about whole year with v6.
