### ISSUE TITLE
Error transforming

### ISSUE THREAD

**Issue by mosh1e** [rollup/rollup-plugin-babel#72] opened 2016-08-05 13:41 UTC
When following the tutorial [here](http://rollupjs.org/guide/#using-rollup-with-babel) I get this error :( being fairly new to transpiling it might be something I have done wrong..

```
>> rollup -c
Error transforming /Applications/MAMP/htdocs/nodejs/src/main.js with 'babel' plugin: It looks like your Babel configuration specifies a module transformer. Please disable it. If you're using the "es2015" preset, consider using "es2015-rollup" instead. See https://github.com/rollup/rollup-plugin-babel#configuring-babel for more information
Error: Error transforming /Applications/MAMP/htdocs/nodejs/src/main.js with 'babel' plugin: It looks like your Babel configuration specifies a module transformer. Please disable it. If you're using the "es2015" preset, consider using "es2015-rollup" instead. See https://github.com/rollup/rollup-plugin-babel#configuring-babel for more information
    at preflightCheck (/Applications/MAMP/htdocs/nodejs/node_modules/rollup-plugin-babel/dist/rollup-plugin-babel.cjs.js:43:102)
    at Object.transform$1 [as transform] (/Applications/MAMP/htdocs/nodejs/node_modules/rollup-plugin-babel/dist/rollup-plugin-babel.cjs.js:104:18)
    at /usr/local/lib/node_modules/rollup/src/utils/transform.js:13:35
    at process._tickCallback (internal/process/next_tick.js:103:7)
    at Function.Module.runMain (module.js:577:11)
    at startup (node.js:160:18)
    at node.js:456:3
```

I have added the preset as it says in the tutorial

**Comment by eventualbuddha** [comment] 2016-08-05 14:08
This was caused by a change to babel's es2015 preset. Here's the fix in babel: https://github.com/babel/babel/pull/3635. That's not all that has to change, though. We need to update babel-preset-es2015-rollup to respect the new format (https://github.com/rollup/babel-preset-es2015-rollup/issues/7). The work is done, just waiting on @Rich-Harris to release a new version.

**Comment by adriantoine** [comment] 2016-08-07 12:56
You don't really need `babel-preset-es2015-rollup` if you use Babel 6.13.0, you can do:
```js
{
  presets: [
    ["es2015", { "modules": false }]
  ]
}
```
in your `.babelrc`.

See: https://github.com/babel/babel/blob/master/CHANGELOG.md#loose-and-modules-options-for-babel-preset-es2015-3331-3627

**Comment by zeitiger** [comment] 2016-08-08 09:00
@adriantoine first, thanks you for you hint. btw. you miss that `external-helper` is also part of `babel-preset-es2015-rollup.
I changed my .babelrc to that 
```
{
  "presets": [
    [
      "es2015",
      {
        "modules": false
      }
    ]
  ],
  "plugins": ["external-helpers"]
}
```

**Comment by adriantoine** [comment] 2016-08-08 09:07
Yeah sorry, I forgot to mention that you have to add `babel-plugin-external-helpers` 😮

**Comment by eventualbuddha** [comment] 2016-08-09 14:22
This is now fixed in babel-preset-es2015-rollup v1.2.0.

On the other hand, you could use [babelrc-rollup](https://github.com/eventualbuddha/babelrc-rollup) instead which allows you to write a babelrc the way you would without rollup, i.e.

```js
{
  "presets": ["es2015"]
}
```

And then do this in your rollup.config.js to configure your babelrc for rollup:

```js
import babel from 'rollup-plugin-babel';
import babelrc from 'babelrc-rollup';

export default {
  …
  plugins: [babel(babelrc())],
  …
};
```

**Closed by eventualbuddha** 2016-08-09 14:22 UTC

**Comment by jamesdixon** [comment] 2017-06-15 18:30
I'm seeing this error even without using the `es2015` preset. Any suggestions?

Here's my babel config:

```js
"babel": {
    "presets": [
      "stage-0"
    ],
    "plugins": [
        "check-es2015-constants",
        "transform-es2015-arrow-functions",
        "transform-es2015-block-scoped-functions",
        "transform-es2015-block-scoping",
        "transform-es2015-computed-properties",
        "transform-es2015-destructuring",
        "transform-es2015-duplicate-keys",
        "transform-class-properties",
        "transform-es2015-for-of",
        "transform-es2015-function-name",
        "transform-es2015-literals",
        "transform-es2015-modules-commonjs",
        "transform-es2015-object-super",
        "transform-es2015-parameters",
        "transform-es2015-shorthand-properties",
        "transform-es2015-spread",
        "transform-es2015-sticky-regex",
        "transform-es2015-template-literals",
        "transform-es2015-typeof-symbol",
        "transform-es2015-unicode-regex",
        "transform-async-to-generator"
    ]
  },
```

**Comment by zeitiger** [comment] 2017-06-19 06:57
I don't see `external-helpers` in your plugin listing. Maybe you should add this too ;-)

**Comment by Inateno** [comment] 2018-03-22 14:22
Hi,

I'm running this error actually, here is the issue I posted in create-react-library https://github.com/DimitriMikadze/create-react-library/issues/28

And here is my babelrc config:

```javascript
{
  "presets": [
    ["env", {
      "modules": false
    }],
    "stage-0",
    "react"
  ],
  "plugins": [
    "external-helpers"
  ]
}
```

And rollup:

```javascript
import babel from 'rollup-plugin-babel'
import commonjs from 'rollup-plugin-commonjs'
import external from 'rollup-plugin-peer-deps-external'
import postcss from 'rollup-plugin-postcss'
import resolve from 'rollup-plugin-node-resolve'
import url from 'rollup-plugin-url'

import pkg from './package.json'

export default {
  input: 'src/index.js',
  output: [
    {
      file: pkg.main,
      format: 'cjs'
    },
    {
      file: pkg.module,
      format: 'es'
    }
  ],
  plugins: [
    external(),
    postcss({
      modules: true
    }),
    url(),
    babel({
      exclude: 'node_modules/**'
    }),
    resolve(),
    commonjs()
  ]
}
```

I'm stuck. Thanks

**Comment by ekampf** [comment] 2018-06-27 00:42
@Inateno did you find a solution?
