### ISSUE TITLE
es2015 preset throws error

### ISSUE THREAD

**Issue by BennyAlex** [rollup/rollup-plugin-babel#159] opened 2017-08-15 15:21 UTC
I have 

```
// .babelrc
{
  "presets": [
    [
      "es2015",
      {
        "modules": false
      }
    ]
  ],
  "plugins": [
    "external-helpers"
  ]
}
```
and get the error:

> (babel plugin) Error: It looks like your Babel configuration specifies a module transformer. Please disable it. See https://github.com/rollup/rollup-plugin-babel#configuring-babel for more information

**Comment by nicohsieh** [comment] 2017-12-29 20:00
I was able to get this working using **babelrc-rollup** https://github.com/eventualbuddha/babelrc-rollup. But it seems like an issue to me that an other helper is needed for it to read .babelrc correctly :/

**Comment by Andarist** [comment] 2017-12-30 17:33
The error might come from some node module, you should share a repository with the issue reproduced so we could investigate and help you.

**Comment by Andarist** [comment] 2018-06-23 17:47
Closing because original author has not provided a repro case. Cannot help without that.

**Closed by Andarist** 2018-06-23 17:47 UTC
