### ISSUE TITLE
Error: Cannot find module '__babelHelpers__'

### ISSUE THREAD

**Issue by PaulBGD** [rollup/rollup-plugin-babel#60] opened 2016-06-10 19:14 UTC
I'm getting this error when trying to use this plugin with a dependency:
```
Error: Cannot find module '__babelHelpers__' from '/home/project/node_modules/preact/src'
```

Using externalHelpers: true fixes this issue, but then I'd have to include the babelHelpers manually (which I don't want.)

**Comment by PaulBGD** [comment] 2016-06-10 19:21
For now I ended up using externalHelpers: true then using the babel helpers cli tool to insert the helpers. The only issue with this is that now rollup doesn't tree shake the helpers.

**Comment by n1ru4l** [comment] 2016-06-12 07:03
I can confirm this issue.

**Comment by raphaelokon** [comment] 2016-06-13 09:05
Same here.

**Comment by n1ru4l** [comment] 2016-06-13 09:44
I switched to webpack,which also supports tree shaking, since I had to much issues with almost everything (I was trying to setup a react application).

I hope future versions of rollup wil work better with modules that do not use es2015 modules already.

**Comment by bedeoverend** [comment] 2016-06-13 12:01
Reverting back to [2.4.0](https://github.com/rollup/rollup-plugin-babel/tree/v2.4.0) fixed it for me

**Comment by raphaelokon** [comment] 2016-06-13 18:09
Webpack is not a solution for me … I fixed it by including externalHelpers manually.

**Comment by d-scott** [comment] 2016-06-22 17:15
Confirmed this using version 2.5.1. 

Also confirmed that with rolling back to 2.4.0, this isn't an issue.

**Comment by Rich-Harris** [comment] 2016-06-23 15:38
Sorry everyone! This should be fixed as of 2.6.0 – `__babelHelpers__` is now `\0babelHelpers`, which adheres to the plugin convention of including a NUL character to signify that it's not a 'real' module. This means that rollup-plugin-node-resolve (and other plugins) will happily ignore it.

Could someone confirm that 2.6.0 does indeed resolve the issue? Thanks

**Comment by bedeoverend** [comment] 2016-06-23 21:57
@Rich-Harris 2.6 has fixed it for me - thanks!

**Comment by Rich-Harris** [comment] 2016-06-23 22:16
@bedeoverend thanks! will close this

**Closed by Rich-Harris** 2016-06-23 22:16 UTC
