### ISSUE TITLE
Inconsistencies with built-ins when using 'usage' mode.

### ISSUE THREAD

**Issue by wtgtybhertgeghgtwtg** [rollup/rollup-plugin-babel#237] opened 2018-08-11 22:10 UTC
Say I have a file like so
```
// input.js
export default async function* () {
  yield Promise.resolve(1);
}
```
and a `.babelrc.js`
```
module.exports = {
  presets: [
    [
      '@babel/env',
      {debug: true, modules: false, targets: {node: '8.6'}, useBuiltIns: 'usage'},
    ],
  ],
};
```
If I transform `input.js` with `@babel/core`
```
const {transformFileSync} = require('@babel/core');
transformFileSync('input.js');
```
the debug will show that the "es7.symbol.async-iterator" polyfill is loaded.  However, this is not the case with `rollup-plugin-babel`
```
const {rollup} = require('rollup');
const babel = require('rollup-plugin-babel');
rollup({input: 'input.js', plugins: [babel()]});
```
I think this is because the `helperPlugin` doesn't do [the stuff Babel usually does if 'helperGenerator' isn't set](https://github.com/babel/babel/blob/8173b6e6943881ae1d95fffd917274c8f99b8eaa/packages/babel-core/src/transformation/file/file.js#L184-L216), so the nodes that'd flag the polyfill as being needed are never injected.

The workaround right now is to use `@babel/plugin-transform-runtime` and let Babel transform it so it picks up on the nodes, but it's pretty hacky and suboptimal.

**Comment by wtgtybhertgeghgtwtg** [comment] 2018-08-25 18:14
Would this repo work?
https://github.com/wtgtybhertgeghgtwtg/rollup-plugin-babel-bug-demo

**Comment by Andarist** [comment] 2018-08-26 19:49
Yeah, this helps a lot! As mentioned this is slightly tricky & I don't have much time lately, but I'll try to tackle this as soon as I can.

**Comment by ali-master** [comment] 2018-09-24 12:06
Hi all.

I have the same problem with babel v7 and rollup babel plugin.
```
[!] (babel plugin) Error: Babel 7.0.0-beta.56 has dropped support for the 'helpersNamespace' utility.If you are using @babel/plugin-external-helpers you will need to use a newer version than the one you currently have installed. If you have your own implementation, you'll want to explore using 'helperGenerator' alongside 'file.availableHelper()'.
```

Does anyone have solution to solve this error?

**Comment by ovac** [comment] 2018-11-18 21:01
I'm having the same issue.

**Comment by ali-master** [comment] 2018-11-18 21:05
I have used the **babel-upgrade** package and works.

**Comment by ovac** [comment] 2018-11-18 21:45
How will I do this? Enlighten me

**Comment by ali-master** [comment] 2018-11-18 21:56
Run the following command:

```bash
npx babel-upgrade --write --install
```

I hope it will be helped you a lot.

**Comment by ovac** [comment] 2018-11-18 22:18
Ok. I did this, but now im stuck with: Error: Cannot find module 'babel-plugin-external-helpers'

**Comment by ali-master** [comment] 2018-11-19 07:35
So, as it said, please install the **babel-plugin-external-helpers** package.

```bash
npm i --save-dev babel-plugin-external-helpers
```

**Comment by ovac** [comment] 2018-11-19 08:10
I did, undid and redid it... 
(babel plugin) Error: Babel 7.0.0-beta.56 has dropped support for the 'helpersNamespace' utility.If you are using @babel/plugin-external-helpers you will need to use a newer version than the one you currently have installed. If you have your own implementation, you'll want to explore using 'helperGenerator' alongside 'file.availableHelper()'.

**Comment by Andarist** [comment] 2018-11-19 09:14
When using babel@7 the usage of `babel-plugin-external-helpers` is not recommended.

I'm not sure if your issue is the exact same issue as described by the original poster - could u provide a repository with your issue reproduced?

**Comment by ovac** [comment] 2018-11-19 10:46
In order to get this to work, I had to copy the config from my .babelrc file into the rollup.config.js and set the "runtimeHelpers" to false. 

in other words: 

```js
import babelrc from 'babelrc-rollup';

plugins: [
 babel(babelrc())
]
```
**was replaced with:** 

```js
runtimeHelpers: false,
plugins: [
  babel({
     "runtimeHelpers": false,
  })
]
```

I'd be glad if I could still use my default .babelrc.
Am I doing something wrong here?

**Comment by Andarist** [comment] 2018-11-19 10:50
It all depends on the structure of your project, for most common case you should be able to just do this:
```js
plugins: [
  babel()
]
```
and that should find your babelrc files.

**Comment by ovac** [comment] 2018-11-19 17:53
@Andarist  and @ali-master thanks so much for your support.
Hello searchers 🤓... My final solution was: 
```js
plugins: [
	//...
	babel(
		babelrc({
			addExternalHelpersPlugin: false,
			exclude: /node_modules/,
			runtimeHelpers: false
		})
	),
	//...
]
```

This is exactly what I was looking for.

**Comment by Andarist** [comment] 2018-12-05 19:01
rollup-plugin-node-resolve if u want to bundle them, or specifying those dependencies as rollup's external option (if u want to keep import statements)

**Comment by zhongs** [comment] 2019-02-04 06:12
@ali-master @ovac I also encountered this problem.

> [!] (babel plugin) Error: Babel 7.0.0-beta.56 has dropped support for the 'helpersNamespace' utility.If you are using @babel/plugin-external-helpers you will need to use a newer version than the one you currently have installed. If you have your own implementation, you'll want to explore using 'helperGenerator' alongside 'file.availableHelper()'.

install babel 6.x  can evade problems
`npm install --save-dev rollup-plugin-babel@3`

**Comment by naecoo** [comment] 2019-05-04 14:51
> @ali-master @ovac I also encountered this problem.
> 
> > [!] (babel plugin) Error: Babel 7.0.0-beta.56 has dropped support for the 'helpersNamespace' utility.If you are using @babel/plugin-external-helpers you will need to use a newer version than the one you currently have installed. If you have your own implementation, you'll want to explore using 'helperGenerator' alongside 'file.availableHelper()'.
> 
> install babel 6.x can evade problems
> `npm install --save-dev rollup-plugin-babel@3`

it solved my problem

**Comment by txs1992** [comment] 2019-07-05 09:54
@ovac You can look at this https://github.com/babel/babel/issues/8908

You should delete "babel-preset-env": "^1.7.0", and do presets: ['@babel/preset-env']

**Comment by Andarist** [comment] 2019-12-17 22:17
I'm not entirely sure if there is any actionable stuff for me here? Could somebody respond back if their issue is still unresolved? If yes then I would appreciate a repro case attached to the reported issue.

**Comment by poradz** [comment] 2020-01-10 13:09
@Andarist you can check this out with YetiForceCRM

1. Clone https://github.com/YetiForceCompany/YetiForceCRM
2. In _public_html/src/package.json_ update _rollup-plugin-babel_ to v4
3. In public_html/src run 
`yarn install`
`yarn run minify-js`
4. The error will appear :)

**Comment by Andarist** [comment] 2020-05-10 09:26
@poradz sorry for not responding earlier. I've missed your comment - the linked repro case is linking to the latest commit of your base branch and some time has passed since then so I won't dive into it now, because your setup probably has changed significantly since then and maybe you have already solved your issue. If the issue persists - please open a new issue at https://github.com/rollup/plugins as we've migrated this plugin there.

Closing this issue because I don't think there is anything actionable on our side here right now, but if you all have any problems with the plugin please open a new, focused, issue with runnable repro cases attached to it at https://github.com/rollup/plugins

**Closed by Andarist** 2020-05-10 09:26 UTC
Labels: bug
