### ISSUE TITLE
v2.5.x causes breakage in conjunction with rollup-plugin-commonjs

### ISSUE THREAD

**Issue by rkirsling** [rollup/rollup-plugin-babel#58] opened 2016-06-08 00:06 UTC
The following example fails as of v2.5:

**package.json**

``` json
{
  "devDependencies": {
    "babel-plugin-external-helpers": "^6.8.0",
    "babel-preset-es2015": "^6.14.0",
    "rollup": "^0.34.13",
    "rollup-plugin-babel": "^2.6.1",
    "rollup-plugin-commonjs": "^4.1.0"
  }
}
```

**.babelrc**

``` json
{
  "presets": [
    ["es2015", { "modules": false }]
  ],
  "plugins": [
    "external-helpers"
  ]
}
```

**rollup.config.js**

``` js
import babel from 'rollup-plugin-babel';
import commonjs from 'rollup-plugin-commonjs';

export default {
  entry: 'main.js',
  plugins: [babel(), commonjs()]
};
```

**main.js**

``` js
import MyLib from './myLib';

console.log('ok');
```

**myLib.js**

``` js
function isObject(o) {
  return (typeof o === 'object');
}

module.exports = { isObject };
```

Running `rollup -c` results in the following error:

```
Error parsing .../myLib.js: 'import' and 'export' may only appear at the top level (10:0) in .../myLib.js
```

This issue was not present in `rollup-plugin-babel@2.4.0`.
It seems related to #55, but is not fixed with `rollup@0.27.1`.

**Comment by rkirsling** [comment] 2016-06-08 19:46
Simplified the example a bit. It seems that `require` may have been a red herring(?)—the crux seems to be **importing a CommonJS module that performs a `typeof` `'object'` check**.

**Comment by rkirsling** [comment] 2016-06-10 18:30
For the record, this is still present in `rollup@0.30.0`.

**Comment by rkirsling** [comment] 2016-08-31 03:01
Updated package.json / .babelrc in the issue description to reflect the latest versions as well as the deprecation of `babel-preset-es2015-rollup`.

This issue still reproes in the same fashion as before.

**Comment by Rich-Harris** [comment] 2016-12-13 18:29
So, I've (finally! sorry) been looking into this, and the problem is with rollup-plugin-commonjs. I've opened an issue over there (https://github.com/rollup/rollup-plugin-commonjs/issues/146), but in the meantime a good workaround is to switch the plugin order so that `commonjs` runs before `babel`. I'll close this in favour of the other issue.

**Closed by Rich-Harris** 2016-12-13 18:29 UTC
