### ISSUE TITLE
"Invalid options type for foreign" error

### ISSUE THREAD

**Issue by yairEO** [rollup/rollup-plugin-babel#83] opened 2016-09-18 15:06 UTC
Node `v5.8.0`
### This is the log:

```
[17:56:29] Starting 'bundleJS'...
[17:56:29] Rollup [catch]:  TypeError: Error transforming C:\www\UI\BUILD\js\dist\app.js with 'babel' plugin: [BABEL] C:
\www\UI\BUILD\js\dist\x.js: Invalid options type for foreign
    at Logger.error (C:\www\UI\BUILD\node_modules\babel-core\lib\transformation\file\logger.js:41:11)
    at OptionManager.mergeOptions (C:\www\UI\BUILD\node_modules\babel-core\lib\transformation\file\options\option-manage
r.js:270:16)
    at C:\www\UI\BUILD\node_modules\babel-core\lib\transformation\file\options\option-manager.js:370:14
    at C:\www\UI\BUILD\node_modules\babel-core\lib\transformation\file\options\option-manager.js:396:22
    at Array.map (native)
    at OptionManager.resolvePresets (C:\www\UI\BUILD\node_modules\babel-core\lib\transformation\file\options\option-mana
ger.js:385:20)
    at OptionManager.mergePresets (C:\www\UI\BUILD\node_modules\babel-core\lib\transformation\file\options\option-manage
r.js:369:10)
    at OptionManager.mergeOptions (C:\www\UI\BUILD\node_modules\babel-core\lib\transformation\file\options\option-manage
r.js:328:14)
    at OptionManager.init (C:\www\UI\BUILD\node_modules\babel-core\lib\transformation\file\options\option-manager.js:481
:10)
    at File.initOptions (C:\www\UI\BUILD\node_modules\babel-core\lib\transformation\file\index.js:211:75)
    at new File (C:\www\UI\BUILD\node_modules\babel-core\lib\transformation\file\index.js:129:22)
    at Pipeline.transform (C:\www\UI\BUILD\node_modules\babel-core\lib\transformation\pipeline.js:48:16)
    at preflightCheck (C:\www\UI\BUILD\node_modules\rollup-plugin-babel\dist\rollup-plugin-babel.cjs.js:41:25)
    at Object.transform$1 [as transform] (C:\www\UI\BUILD\node_modules\rollup-plugin-babel\dist\rollup-plugin-babel.cjs.
js:104:18)
    at C:\www\UI\BUILD\node_modules\rollup\dist\rollup.js:6992:35
    at lib$es6$promise$$internal$$tryCatch (C:\www\UI\BUILD\node_modules\es6-promise\dist\es6-promise.js:362:16)
[17:56:29] Finished 'bundleJS' after 168 ms
```
### And this is my Gulp Rollup plugin:

```
babelRollup({
    presets        : [['es2015', {"modules": false}]], //['es2015-rollup'],
    runtimeHelpers : true,
    exclude        : 'node_modules/**'
})
```

**Comment by sylvainpolletvillard** [comment] 2016-09-19 11:37
Hi, can you explain what you did to solve this issue ? Thanks

**Comment by yairEO** [comment] 2016-09-22 08:17
@sylvainpolletvillard  I think I might have installed `Node 5` instead of `6` and it helped (if my memory serves me)

**Comment by letmaik** [comment] 2016-10-20 11:56
@yairEO Upgrading didn't help for me.

**Comment by letmaik** [comment] 2016-10-20 13:07
I solved the problem by removing the `node_modules` folder and doing a clean install. Shouldn't be necessary, but who knows.

**Comment by yairEO** [comment] 2016-11-11 21:35
LOL I forgot how I solved this, or that I ever had this problem, and today it happened again. I googled and came here and was surprised 

![giphy](https://cloud.githubusercontent.com/assets/845031/20230982/77aa750c-a867-11e6-9fb1-a5cf84564222.gif)

**Comment by chrisdavies** [comment] 2016-12-09 11:49
For me, I had copied a bad example `.babelrc`:

```
{
  "presets": [
    [
      "es2015",
      {
        "modules": false
      }
    ],
    "stage-2",
    "react"
  ]
}
```

Changing it to this got me past this error and on to the next one:

```
{
  "presets": [
    "es2015",
    "stage-2",
    "react"
  ]
}
```

**Comment by Rich-Harris** [comment] 2016-12-13 03:21
I released v3.0.0 today which behaves somewhat differently – @yairEO can you let us know if you're still experiencing the issue, or if we can close this issue? Thanks

**Comment by whatisjasongoldstein** [comment] 2017-05-28 14:49
I'm stuck on what I think is the same issue. I have an identical setup that works in one project and not in another, and the error message is meaningless.

```
UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: [BABEL] /Users/myusername/dev/sites/mysite/frontend/js/x.js: Invalid options type for foreign
```

The mind-boggling part is `x.js` doesn't exist. Nor should it.

Here's what I've got:

```
// Gulp task
gulp.task('scripts', function() {
    rollup({
      entry: 'frontend/js/app.js',
      plugins: [
          nodeResolve({
          jsnext: true,
          browser: true,
        }),
        babelRollup({})
      ]
    }).then(function (bundle) {
        return bundle.write({
          format: "iife",
          dest: "dist/js/app.js",
          sourceMap: true,
        });
    });
});
```

`app.js` exists and is currently just a `console.log`.

```
// .babelrc
{
  "presets": [
    [
      "es2015",
      {
        "modules": false
      }
    ]
  ],
  "plugins": [
    "external-helpers"
  ]
}
```

Wiping out node_modules and reinstalling node modules doesn't help.

Any ideas?

**Comment by yowainwright** [comment] 2017-08-13 00:56
@Rich-Harris I'm having this issue with `v3.0.0`.

I run `rollup -c --environment entry:[a name]` and bundling fails :

Here's my error output:
```shell
TypeError: [BABEL] /Users/jwainwright/code/scrolldir/src/x.js: Invalid options type for foreign
    at error (/Users/jwainwright/code/scrolldir/node_modules/rollup/dist/rollup.js:181:12)
    at Object.error$1 [as error] (/Users/jwainwright/code/scrolldir/node_modules/rollup/dist/rollup.js:9415:6)
    at /Users/jwainwright/code/scrolldir/node_modules/rollup/dist/rollup.js:9424:32
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:169:7)
    at Function.Module.runMain (module.js:607:11)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3
```
[Here's the commit sha from my repository for reference](https://github.com/dollarshaveclub/scrolldir/commit/2361bc300f4be498831aeb6b1045628e2f56734c)


When I reverted back to version `2.6.1` I'm good to go! 👍

Let me know if I can help!

**Comment by Andarist** [comment] 2018-06-23 15:43
I've tried to reproduce on given commit, but without success. Closing this issue because it's old and there is high chance that it doesn't happen anymore. If it does - please create new one.

**Closed by Andarist** 2018-06-23 15:43 UTC

**Comment by yowainwright** [comment] 2018-06-23 17:40
Thanks for your help with this @Andarist.
