### ISSUE TITLE
externalHelpers does not work.

### ISSUE THREAD

**Issue by conartist6** [rollup/rollup-plugin-babel#245] opened 2018-09-01 20:35 UTC
I would expect that when I use esmodule helpers and `externalHelpers: true` this would be the equivalent of setting: the rollup `external` setting in such a way that it would cover the esm runtime helpers, however this is not the case. `externalHelpers` does not do anything that I can detect.

**Comment by Andarist** [comment] 2018-09-03 08:12
Which version of babel (and this plugin) do u use?

**Comment by littlespex** [comment] 2018-10-08 18:46
I am experiencing a similar issue when trying to update our build process to use babel 7. When I configure rollup/babel with `externalHelpers: true` the helpers are still being inserted at the top of the bundled js. I've also tried using the `external-helpers` plugin, but I'm get the following message: 
> Using "external-helpers" plugin with rollup-plugin-babel is deprecated, as it now automatically deduplicates your Babel helpers.
I am developing an app that has multiple runtime plugins which are also bundled using rollup and the helper functions are duplicated in every file. The external helper functionality worked in previous versions of rollup/babel.

**Comment by Andarist** [comment] 2018-10-08 21:40
Could you paste in your babel@6 rollup config + babel config? I should be able to tell you how to migrate it to babel@7.

`externalHelpers` is a setting which allows true external helpers (how babel defines them), but they are **global** and IMHO should be discouraged. Using `babel-plugin-external-helpers` with rollup-plugin-babel@3 was a hacky solution for the problem - it overloaded what `babel-plugin-external-helpers` is actually doing.

If you want to dedupe your helpers I advise to use `@babel/plugin-transform-runtime` and `runtimeHelpers: true`, you can check out how to do that here https://github.com/andreypopp/react-textarea-autosize/blob/0ecbdb1ffb29ad2489b4edea7801360f51a06ea2/rollup.config.js#L40-L49

**Comment by littlespex** [comment] 2018-10-08 22:38
`plugin-transform-runtime` did the trick. Thanks @Andarist.

**Comment by Andarist** [comment] 2018-10-09 07:07
Closing this issue then, as original author of the thread has not responded with requested information.

**Closed by Andarist** 2018-10-09 07:07 UTC

**Comment by aparajita** [comment] 2019-01-19 20:04
This was a regression in the plugin which has been fixed in 4.3.2. No need to use `@babel/plugin-transform-runtime` as a workaround.

**Comment by webwyb** [comment] 2019-09-06 03:28
By default externalHelpers option is set to false so babel helpers will be included in your bundle.

If you do not wish the babel helpers to be included in your bundle at all (but instead reference the global babelHelpers object), you may set the externalHelpers option to true:

rollup.rollup({
  ...,
  plugins: [
    babel({
      plugins: ['external-helpers'],
      externalHelpers: true
    })
  ]
}).then(...)
