### ISSUE TITLE
Typeof transform

### ISSUE THREAD

**Issue by scola84** [rollup/rollup-plugin-babel#69] opened 2016-08-01 06:54 UTC
When I try to transform code with `typeof a === 'symbol'` in it, the output of rollup-plugin-babel becomes erroneous. In the second example below, `var typeof = ...` is wrong. I suppose it has to do with https://github.com/rollup/rollup-plugin-babel/blob/master/src/index.js#L43? 

With `babel`:

```
var _typeof = typeof Symbol === "function" && typeof Symbol.iterator === "symbol" ? function (obj) { return typeof obj; } : function (obj) { return obj && typeof Symbol === "function" && obj.constructor === Symbol ? "symbol" : typeof obj; };
```

With `rollup-plugin-babel`:

```
var typeof = typeof Symbol === "function" && typeof Symbol.iterator === "symbol" ? function (obj) {
  return typeof obj;
} : function (obj) {
  return obj && typeof Symbol === "function" && obj.constructor === Symbol ? "symbol" : typeof obj;
};
```

The transform is triggered by https://github.com/babel/babel/tree/master/packages/babel-plugin-transform-es2015-typeof-symbol

**Comment by eventualbuddha** [comment] 2016-08-09 19:33
Can you provide some more information? What do your `rollup.config.js`, `.babelrc`, and input file look like?

**Comment by derduher** [comment] 2016-08-14 01:51
I am running into the same issue so I'll chime in with those files. I'll note I'm only running into the issue with karma-rollup-preprocessor which has rollup@0.26.7
I'm pretty sure OP either is using the same or is on an older version. I'll see if I can open an update against karma-rollup-preprocessor
```
{
  presets: [ "es2015-rollup" ],
  sourceMaps: true
}
```
and 
```
import babel from 'rollup-plugin-babel'
export default {
  entry: 'src/index.js',
  format: 'cjs',
  plugins: [babel()],
  dest: 'bundle.js' // equivalent to --output
}
```

```
    preprocessors: {
      'tests/**/*.js': [ 'rollup' ]
    },
    rollupPreprocessor: {
      rollup: {
        plugins: [
          require('rollup-plugin-babel')({
            presets: [
              require('babel-preset-es2015-rollup')
            ]
          })
        ]
      },
      bundle: {
        sourceMap: 'inline'
      }
    },
```

**Comment by derduher** [comment] 2016-08-14 01:55
I've just confirmed that forcing the dep of karma-rollup-preprocessor to the latest resolves the issue

**Comment by scola84** [comment] 2016-09-03 09:42
Sorry for not getting back sooner. I tried to reliably reproduce this problem: what I found out is that the problem relates to the 'lodash-es' package and that the problem disappears when I upgrade the 'rollup' package from '0.26.3' to '0.34.13'. I suggest to close this issue and never look back.

**Comment by differui** [comment] 2016-11-04 08:19
When I use [clipboard](https://zenorocha.github.io/clipboard.js) reporduct same error message:

```
Uncaught TypeError: _typeof is not a function(…)
```

**Comment by Hilzu** [comment] 2016-11-05 16:21
I was trying to build a React project using react-router with rollup and hit this bug. I created a minimal reproduction in this [gist](https://gist.github.com/Hilzu/64787686a670fbe59e170214a88f8dc3). I copied the mod.js typeof code from react-routers history dependency.

**Comment by alexnaish** [comment] 2016-12-17 14:09
Just hit this issue with react-router too. The bundle builds fine but results in an `Uncaught TypeError: _typeof is not a function` error in the console.

**Comment by maxval94** [comment] 2018-03-13 10:24
I have the same problem 
`No name was provided for external module 'babel-runtime/core-js/json/stringify' in options.globals – guessing '_JSON$stringify'`
`No name was provided for external module 'babel-runtime/helpers/typeof' in options.globals – guessing '_typeof'`

My config 
```javascript
{
  presets: [
    [
      "env",
      {
        targets: {
          browsers: ["> 5%", "since 2015"]
        },
        modules: false
      }
    ]
  ],
  runtimeHelpers: true
}
```

**Comment by Andarist** [comment] 2018-06-21 22:21
Closing this as outdated and not actionable due to lack of reproduction case. Feel free to open new issue.

**Closed by Andarist** 2018-06-21 22:21 UTC
Labels: bug, more information needed
