### ISSUE TITLE
Weird export removal in conjuction with rollup-plugin-babel@1

### ISSUE THREAD

**Issue by RReverser** [rollup/rollup-plugin-babel#36] opened 2016-01-27 14:01 UTC
I tried to minimize the test case to the minimal reproducible example, so sorry for the somewhat obscure code. This is reproducible with more complex structure (and `import` / `export` in separate files) as well.

Say, I have file `answer.js`:
```javascript
export const answer = 42;
```

And `index.js`:
```javascript
export { answer as exportedAnswer } from "./answer"
import { answer as importedAnswer } from "./answer"

export function doSmth() {
  let value
  value = importedAnswer;
  console.log(value);
}
```

And I use a simple build script `build.js` for bundling with `rollup-plugin-babel@1`:
```javascript
require('rollup').rollup({
  entry: 'index.js',
  plugins: [require('rollup-plugin-babel')()]
}).then(bundle => bundle.write({
  format: 'cjs',
  dest: 'dist.js'
}));
```

In that case output `dist.js` with `rollup-plugin-babel@1` applied and CommonJS as output format looks like:
```javascript
'use strict';

answer = 42;

function doSmth() {
  var value = undefined;
  value = exports.exportedAnswer;
  console.log(value);
}

exports.doSmth = doSmth;
```

You can see a couple of problems here:
* `answer` is assigned to, but not actually declared as variable
* `exportedAnswer` was not exported at all
* `exportedAnswer` is still being (incorrectly) referred to from `doSmth`

Things tried:
* splitting `export` and `import` statements from `index.js` into separate files (`index.js` just re-exports, other file imports and uses) - doesn't help
* reordering `export` and `import` - doesn't help
* not exporting `doSmth` - it gets removed as unused in the output, but doesn't help for `exportedAnswer`
* unwrapping `doSmth` code from a function into a regular module code - doesn't help
* merging variable declaration and assignment of `value` - weirdly helps, but this is not always feasible in real code

P.S. In `rollup-plugin-babel@2` (or without plugins at all), `exports.exportedAnswer = 42` is generated instead of `answer = 42`, so generated code is valid and works, although not very optimized as, when having lots of code, all the references to local variable get replaced with `exports.<somename>` property access. Although this is probably a separate question, unrelated to this repo.

**Comment by RReverser** [comment] 2016-01-30 00:15
@Rich-Harris Haha, just saw the online `Default exports` sample. And I thought I'm the only one who uses `answer` and `42` as stubs :smile:

**Comment by Rich-Harris** [comment] 2016-01-31 17:47
> And I thought I'm the only one who uses `answer` and `42` as stubs

Great minds think alike!

Thanks for the simple repro. It's a bug in Rollup itself rather than this plugin (it just so happens that Babel 5 produces output that exposes the bug), so I'll close this in favour of https://github.com/rollup/rollup/issues/484, which is fixed via https://github.com/rollup/rollup/pull/485.

The root of the issue is that Rollup detects when an exported value might change after it's been exported, so that it can [preserve live bindings](http://rollupjs.org/#%7B%22options%22%3A%7B%22format%22%3A%22cjs%22%2C%22moduleName%22%3A%22myBundle%22%2C%22globals%22%3A%7B%7D%7D%2C%22modules%22%3A%5B%7B%22name%22%3A%22main.js%22%2C%22code%22%3A%22%2F%2F%20all%20the%20references%20to%20%60count%60%20get%20rewritten%20as%5Cn%2F%2F%20%60exports.count%60%2C%20so%20that%20any%20consumer%20of%20this%5Cn%2F%2F%20module%20gets%20the%20correct%20value%20as%20long%20as%20it%5Cn%2F%2F%20refers%20to%20%60importedModule.count%60%5Cnexport%20var%20count%20%3D%200%3B%5Cnexport%20function%20increment%20()%20%7B%5Cn%20%20return%20count%2B%2B%3B%5Cn%7D%22%7D%5D%7D) without using ES5 accessors. (In this case it looks like it's getting a false positive – not sure why, need to look into it.) So all the references to `answer` get rewritten to `exports.exportedAnswer` – false positive aside, this is expected behaviour, even though it bulks up the code a bit. The fact that `answer` isn't declared and `exportedAnswer` is never exported are two manifestations of the same bug that's fixed in https://github.com/rollup/rollup/pull/485.

**Closed by Rich-Harris** 2016-01-31 17:47 UTC

**Comment by RReverser** [comment] 2016-01-31 18:05
Oh cool. Wasn't sure whether it's a bug in Rollup or this plugin, but could only reproduce with only this plugin and only specific version, so assumed that's it - sorry for posting in the wrong repo then.

Thanks for the detailed explanation and a fix.

**Comment by RReverser** [comment] 2016-01-31 18:06
By the way, as for the `P.S.` part - is this something I should post as an issue or is it by-design?

**Comment by Rich-Harris** [comment] 2016-01-31 18:53
Theoretically, though it gets hellishly complex in situations like this (contrived but you get the idea):

```js
export var count = 0;
export function incrementByThree () {
  var a = count++, b = count++, c = count++;
  return c;
}
```

You get into some slightly gnarly AST manipulation territory. Rollup doesn't actually manipulate ASTs, it just manipulates a string (using the AST as a guide, with [magic-string](https://github.com/Rich-Harris/magic-string)), so it gets even trickier. I wouldn't rule it out as a future improvement though.

**Comment by RReverser** [comment] 2016-01-31 19:31
Hm, `magic-string` looks interesting (although a bit scary - does it respect comments and other tokens that are not source code?).

As for your example - yeah, this might be tricky (although doable).

**Comment by Rich-Harris** [comment] 2016-01-31 19:42
It doesn't have any concept of comments etc – all it does is allow you to progressively replace substrings in a way that preserves character indices (i.e. you can remove characters 10-20, then remove characters 25-35 without having to account for the fact that you've already removed ten characters) and generates a sourcemap. So if you have an AST node like this...

```js
{ "type": "Identifier", "start": 20, "end": 23, "name": "something" }
```

...you can do `magicString.overwrite(node.start, node.end, 'somethingElse')` and it will leave everything else untouched. The value of it is that there's no codegen step, so a) it's blazing fast, and b) the original formatting is completely untouched. And because it's totally language-agnostic it can be used for other things, e.g. [converting CoffeeScript](https://github.com/decaffeinate/decaffeinate).

**Comment by RReverser** [comment] 2016-01-31 21:13
> the original formatting is completely untouched

That's what I'm asking about. I mean, if you have text that matches your searched pattern within a comment, it will be replaced too (even though it's not a code), so comment will not be preserved, right?

**Comment by Rich-Harris** [comment] 2016-01-31 21:25
Sure. The expectation is that you wouldn't do a blind search-and-replace, but would traverse an AST to find which character ranges needed to be replaced. I wrote [tippex](https://github.com/rich-harris/tippex) for times when you don't want to do a full traversal but also don't want to deal with comments etc.

**Comment by RReverser** [comment] 2016-01-31 22:16
Gotcha. Interesting approach (but scary, pretty much like parsing HTML with regexps :) ).
P.S. I might be just too opinionated in the parsing topic.
