### ISSUE TITLE
Unable to use Class Properties Transform ES2015 feature

### ISSUE THREAD

**Issue by mikeycgto** [rollup/rollup-plugin-babel#89] opened 2016-10-11 21:04 UTC
I'm using rollup with babel on a React project. For some reason I am unable to use this feature: http://babeljs.io/docs/plugins/transform-class-properties/

Here is my babel plugin configuration:

```
babel({
    exclude: 'node_modules/**',

    presets: ['es2015-rollup', 'react', 'stage-2'],
    plugins: ['external-helpers'],
    babelrc: false
})
```

Here is my class definition:

```
export class App extends React.Component {
    state = {
        value: 'search'
    };
}
```

And here is the error I am getting.

```
/home/user/Projects/test-application/src/containers/App.jsx
  4:11  error  Parsing error: Unexpected token =

✖ 1 problem (1 error, 0 warnings)
```

I've used this feature before with the `es2015`, `react`, and `stage-2` presets on a project using webpack. Any ideas?

**Comment by pubkey** [comment] 2016-11-26 20:58
I also had this error with es6-static-functions.
``` missing class properties transform ```
I got it working with this rollup-config:

```js
export default {
    moduleName: 'foobar',
    entry: 'src/index.js',
    dest: 'dist/rollup-bundle.js',
    plugins: [
        babel({
            exclude: 'node_modules/**',
            presets: ['es2015-rollup', 'stage-0'],              //  <- stage-0 had to be added
            runtimeHelpers: true
        }),
        uglify()
    ]
}
```

**Comment by jmagoon** [comment] 2017-06-21 17:09
i had this problem and it was a super simple fix due to me being dumb. i had to reorder the plugins in the rollup config file to have babel before commonjs

**Comment by michaeldzjap** [comment] 2017-12-10 15:23
@jmagoon's solution worked for me. However, it says in the rollup documentation:

> Note that rollup-plugin-commonjs should go before other plugins that transform your modules — this is to prevent other plugins from making changes that break the CommonJS detection.

Kind of confusing...

**Comment by goliney** [comment] 2018-03-28 20:07
Reordering didn't help me. When I put `babel` before `commonjs`, I started getting this:
```
src/main.js → dist/qrize.umd.js...
[!] Error: 'default' is not exported by node_modules/qrcode-generator/qrcode.js
https://github.com/rollup/rollup/wiki/Troubleshooting#name-is-not-exported-by-module
src/main.js (3:7)
1: // @flow
2: 
3: import qrcode from "qrcode-generator";
          ^
4: import { version as pkgVersion } from "../package.json";
5: import { getJSON, prepareCallback } from "./requests";

```

**Comment by n1313** [comment] 2018-06-18 11:20
In my case I forgot to call `super(props);` in my component constructor, and that was the problem.

**Comment by Andarist** [comment] 2018-06-21 22:06
Overally it seems like the issue is resolved. It's known how to workaround this (reordering). I'm going to close this issue - if you think it shouldnt get closed please raise a new issue and link to this one.

**Closed by Andarist** 2018-06-21 22:06 UTC
